
// FUNÇÕES NECESSÁRIAS:

// ATUALIZAR HISTÓRICO DE VIAGENS PASSAGEIRO(
//     UIDMOTORISTA;
//     DATAVIAGEM;
//     NOME DO MOTORISTA;
//     DESTINO DO PASSAGEIRO;
//     LINK DA FOTO DE PERFIL DO MOTORISTA;
//     REFERENCIA DA VIAGEM;
//     )
    
// ATUALIZAR HISTÓRICO DE VIAGENS MOTORISTA(
//     ?
// )